language: java
jdk:
 - openjdk13
 # add other jdk here

services:
  - xvfb

before_install:
 - sudo apt update
 - sudo apt install openjfx
 - sudo apt install at-spi2-core
 - chmod +x gradlew   # add exe permission to graglew
 - export DISPLAY=:99.0

install: true
 
# good for performances
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
addons:
  sonarcloud:
    organization: "fnx-hub"
    token:  $SONAR_TOKEN
    
#launch the scripts
script:
  - ./gradlew clean check jacocoTestReport sonarqube build